#!/usr/bin/env python3
"""Download the site's webfonts and generate a local @font-face stylesheet.

Loading fonts from Google costs two extra DNS+TLS handshakes on every page and
delays first paint. Self-hosting removes both, which is a ranking factor now and
an ad-viewability factor once ads run. Both families are open-licensed (SIL OFL),
so redistributing them from our own domain is permitted.

Run:  python tools/fetch_fonts.py
"""

import re
import sys
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT = ROOT / "static" / "fonts"
CSS_OUT = ROOT / "static" / "fonts.css"

# A modern UA is required or Google serves legacy TTF instead of woff2.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")

# Only the weights and styles the stylesheet actually uses. Every extra face is
# a file the browser may download for nothing.
FAMILIES = (
    "Cormorant+Garamond:ital,wght@0,400;0,600;1,400"
    "&family=Spectral:ital,wght@0,300;0,600;1,400"
)

# Latin covers the site's text including macrons (mystēria) and accented Greek
# transliteration. Add "greek" here if a post ever needs actual Greek script.
WANTED_SUBSETS = {"latin", "latin-ext"}

FACE_RE = re.compile(r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})", re.DOTALL)


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read() if binary else r.read().decode("utf-8")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    css_url = f"https://fonts.googleapis.com/css2?family={FAMILIES}&display=swap"

    try:
        css = fetch(css_url)
    except Exception as e:
        print(f"  could not reach Google Fonts: {e}")
        sys.exit(1)

    blocks, total = [], 0
    for subset, face in FACE_RE.findall(css):
        if subset not in WANTED_SUBSETS:
            continue

        src = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", face)
        if not src:
            continue
        remote = src.group(1)

        family = re.search(r"font-family:\s*'([^']+)'", face).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", face)
        style = re.search(r"font-style:\s*(\w+)", face)
        weight = weight.group(1) if weight else "400"
        style = style.group(1) if style else "normal"

        slug = family.lower().replace(" ", "-")
        name = f"{slug}-{weight}{'-italic' if style == 'italic' else ''}-{subset}.woff2"
        dest = OUT / name

        if not dest.exists():
            dest.write_bytes(fetch(remote, binary=True))
        total += dest.stat().st_size

        local = face.replace(remote, f"/static/fonts/{name}")
        local = re.sub(r"format\('woff2'\)", "format('woff2')", local)
        blocks.append(f"/* {family} {weight} {style} / {subset} */\n{local}")
        print(f"  ok  {name:52} {dest.stat().st_size // 1024:>3} KB")

    if not blocks:
        print("  no faces matched — check FAMILIES / WANTED_SUBSETS")
        sys.exit(1)

    CSS_OUT.write_text(
        "/* Generated by tools/fetch_fonts.py — do not edit by hand.\n"
        "   Cormorant Garamond and Spectral are licensed under the SIL Open Font\n"
        "   License 1.1, which permits self-hosting and redistribution. */\n\n"
        + "\n\n".join(blocks) + "\n",
        encoding="utf-8")

    print(f"\n  {len(blocks)} faces, {total // 1024} KB -> static/fonts/")
    print(f"  stylesheet -> static/fonts.css")


if __name__ == "__main__":
    main()
